#!/usr/bin/env node

import fs from 'node:fs/promises';
import { constants as fsConstants } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';

const marker = 'Generated by xilixili-publisher';
const label = 'com.xilixili.publisher';
const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDir, '..');
const uid = process.getuid?.() ?? 501;
const domain = `gui/${uid}`;
const homeDir = os.homedir();
const launchAgentDir = path.join(homeDir, 'Library', 'LaunchAgents');
const plistPath = path.join(launchAgentDir, `${label}.plist`);
const binDir = path.join(homeDir, '.local', 'bin');
const localDir = path.join(projectRoot, '.local');
const logDir = path.join(localDir, 'logs');
const nodeExecutable = process.execPath;
const serverEntry = path.join(projectRoot, 'dist', 'server', 'index.js');
const cliEntry = path.join(projectRoot, 'dist', 'cli', 'index.js');
const dailyEntry = path.join(projectRoot, 'dist', 'cli', 'daily.js');
const weeklyEntry = path.join(projectRoot, 'dist', 'cli', 'weekly.js');
const engagementEntry = path.join(projectRoot, 'dist', 'cli', 'engagement.js');
const skillSource = path.join(projectRoot, 'skills', 'xilixili-daily-ops');
const skillTarget = path.join(homeDir, '.codex', 'skills', 'xilixili-daily-ops');

function xml(value) {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;');
}

function run(command, args, allowFailure = false) {
  const result = spawnSync(command, args, { encoding: 'utf8' });
  if (result.error) throw result.error;
  if (result.status !== 0 && !allowFailure) {
    const detail = (result.stderr || result.stdout || '').trim();
    throw new Error(`${command} ${args.join(' ')} 失败${detail ? `\n${detail}` : ''}`);
  }
  return result;
}

async function exists(target, mode = fsConstants.F_OK) {
  return fs.access(target, mode).then(() => true).catch(() => false);
}

async function assertManagedOrAbsent(target) {
  if (!await exists(target)) return;
  const content = await fs.readFile(target, 'utf8').catch(() => '');
  if (!content.includes(marker)) {
    throw new Error(`拒绝覆盖不属于本项目的文件：${target}`);
  }
}

function buildPlist() {
  const runtimePath = [path.dirname(nodeExecutable), process.env.PATH ?? '/usr/local/bin:/usr/bin:/bin']
    .join(':');
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- ${marker} -->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${label}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${xml(nodeExecutable)}</string>
    <string>${xml(serverEntry)}</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${xml(projectRoot)}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>${xml(runtimePath)}</string>
    <key>XILIXILI_PROJECT_ROOT</key>
    <string>${xml(projectRoot)}</string>
  </dict>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>LimitLoadToSessionType</key>
  <string>Aqua</string>
  <key>ProcessType</key>
  <string>Interactive</string>
  <key>ThrottleInterval</key>
  <integer>10</integer>
  <key>StandardOutPath</key>
  <string>${xml(path.join(logDir, 'service.out.log'))}</string>
  <key>StandardErrorPath</key>
  <string>${xml(path.join(logDir, 'service.err.log'))}</string>
</dict>
</plist>
`;
}

function buildCommand(entryUrl) {
  return `#!${nodeExecutable}
// ${marker}
await import(${JSON.stringify(entryUrl)});
`;
}

async function writeManagedFile(target, content, mode) {
  await assertManagedOrAbsent(target);
  await fs.writeFile(target, content, { encoding: 'utf8', mode });
  await fs.chmod(target, mode);
}

async function installSkill() {
  const sourceManifest = path.join(skillSource, 'SKILL.md');
  if (!await exists(sourceManifest, fsConstants.R_OK)) {
    throw new Error(`项目技能源文件不存在：${sourceManifest}`);
  }
  const targetManifest = path.join(skillTarget, 'SKILL.md');
  if (await exists(targetManifest)) {
    const current = await fs.readFile(targetManifest, 'utf8').catch(() => '');
    if (!current.includes('name: xilixili-daily-ops')) {
      throw new Error(`拒绝覆盖不属于本项目的技能：${skillTarget}`);
    }
  }
  await fs.mkdir(path.dirname(skillTarget), { recursive: true, mode: 0o700 });
  await fs.cp(skillSource, skillTarget, { recursive: true, force: true });
}

async function install() {
  const requiredBuild = [
    serverEntry,
    cliEntry,
    dailyEntry,
    weeklyEntry,
    engagementEntry,
    path.join(projectRoot, 'web', 'dist', 'index.html'),
    path.join(skillSource, 'SKILL.md'),
  ];
  const missing = [];
  for (const target of requiredBuild) if (!await exists(target, fsConstants.R_OK)) missing.push(target);
  if (missing.length) throw new Error(`生产构建不完整，请先运行 npm run build：\n${missing.join('\n')}`);

  await fs.mkdir(launchAgentDir, { recursive: true });
  await fs.mkdir(binDir, { recursive: true, mode: 0o755 });
  await fs.mkdir(logDir, { recursive: true, mode: 0o700 });
  await assertManagedOrAbsent(plistPath);
  await fs.writeFile(plistPath, buildPlist(), { encoding: 'utf8', mode: 0o600 });
  await fs.chmod(plistPath, 0o600);

  await writeManagedFile(
    path.join(binDir, 'xilixili'),
    buildCommand(pathToFileURL(cliEntry).href),
    0o755,
  );
  await installSkill();
  await writeManagedFile(
    path.join(binDir, 'xilixili-daily'),
    buildCommand(pathToFileURL(dailyEntry).href),
    0o755,
  );
  await writeManagedFile(
    path.join(binDir, 'xilixili-weekly'),
    buildCommand(pathToFileURL(weeklyEntry).href),
    0o755,
  );
  await writeManagedFile(
    path.join(binDir, 'xilixili-engagement'),
    buildCommand(pathToFileURL(engagementEntry).href),
    0o755,
  );
  await writeManagedFile(
    path.join(binDir, 'xilixili-service'),
    buildCommand(import.meta.url),
    0o755,
  );

  run('/usr/bin/plutil', ['-lint', plistPath]);
  run('/bin/launchctl', ['bootout', domain, plistPath], true);
  run('/bin/launchctl', ['bootstrap', domain, plistPath]);
  run('/bin/launchctl', ['enable', `${domain}/${label}`]);
  run('/bin/launchctl', ['kickstart', '-k', `${domain}/${label}`]);
  console.log(`已安装并启动：http://127.0.0.1:4317\n系统命令：${path.join(binDir, 'xilixili')}\nCodex 技能：${skillTarget}`);
}

async function start() {
  if (!await exists(plistPath)) throw new Error('系统服务尚未安装，请先运行 npm run system:install。');
  const current = run('/bin/launchctl', ['print', `${domain}/${label}`], true);
  if (current.status !== 0) run('/bin/launchctl', ['bootstrap', domain, plistPath]);
  run('/bin/launchctl', ['kickstart', '-k', `${domain}/${label}`]);
  console.log('洗哩洗哩运营台服务已启动。');
}

async function stop() {
  run('/bin/launchctl', ['bootout', domain, plistPath], true);
  console.log('洗哩洗哩运营台服务已停止，配置仍保留。');
}

async function restart() {
  await stop();
  await start();
}

async function healthReady() {
  try {
    const response = await fetch('http://127.0.0.1:4317/api/health', { signal: AbortSignal.timeout(2_000) });
    return response.ok ? await response.json() : undefined;
  } catch {
    return undefined;
  }
}

async function status() {
  const loaded = run('/bin/launchctl', ['print', `${domain}/${label}`], true).status === 0;
  const health = await healthReady();
  console.log(JSON.stringify({
    installed: await exists(plistPath),
    loaded,
    healthy: Boolean(health?.ok),
    url: 'http://127.0.0.1:4317',
    pid: loaded ? Number(run('/bin/launchctl', ['print', `${domain}/${label}`], true).stdout.match(/\bpid = (\d+)/)?.[1] ?? 0) || undefined : undefined,
    health,
    plist: plistPath,
    logs: logDir,
  }, null, 2));
  if (!loaded || !health?.ok) process.exitCode = 1;
}

async function removeManagedFile(target) {
  if (!await exists(target)) return;
  const content = await fs.readFile(target, 'utf8').catch(() => '');
  if (content.includes(marker)) await fs.unlink(target);
}

async function uninstall() {
  run('/bin/launchctl', ['bootout', domain, plistPath], true);
  await removeManagedFile(plistPath);
  await removeManagedFile(path.join(binDir, 'xilixili'));
  await removeManagedFile(path.join(binDir, 'xilixili-daily'));
  await removeManagedFile(path.join(binDir, 'xilixili-weekly'));
  await removeManagedFile(path.join(binDir, 'xilixili-engagement'));
  await removeManagedFile(path.join(binDir, 'xilixili-service'));
  console.log('已卸载系统服务和命令；.local 中的账号资料、状态和日志已保留。');
}

function usage() {
  console.log(`用法：xilixili-service <install|start|stop|restart|status|uninstall>`);
}

const command = process.argv[2];
try {
  if (command === 'install') await install();
  else if (command === 'start') await start();
  else if (command === 'stop') await stop();
  else if (command === 'restart') await restart();
  else if (command === 'status') await status();
  else if (command === 'uninstall') await uninstall();
  else usage();
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
}
